[general]
import = ["alacrittyCommonSettings.toml"]

working_directory = "C:\\Users\\bjame\\repos\\github"

[terminal.shell] 
#program = "C:\\Program Files\\Git\\bin\\bash.exe"
program = "cmd.exe"
args =  [
    "/k", 
    "C:\\Users\\bjame\\repos\\github\\dotfiles\\cmd\\bat\\cmdsetup.bat"
    ]