#[general]
#working_directory = "C:\\Users\\bjame"

#[terminal]
#shell = "C:\\Program Files\\Git\\bin\\bash.exe"

#[env]

[window]
opacity = 0.9
blur = true
startup_mode = "Maximized"

[scrolling]
history = 10000

[font]
size = 14

[colors.primary]
#background = "0x2D2A3E"
background = "0x000000"
foreground = "0xfff1f3"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Block", blinking = "Always"}
vi_mode_style = {shape = "Beam", blinking = "Always"}
